### ISSUE TITLE
Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE:generateTests

### ISSUE THREAD

**Issue by patpatpat123** [wkorando/produce-service#1]
Hello,

First of all, thank you for this project and the talk you did at Spring Developer.
I am trying to run contract testing among my team.
After git pulling your project, a simple mvn clean install yields a :
[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE:generateTests (default-generateTests) on project produce-service: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE:generateTests failed: A required class was missing while executing org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE:generateTests: wiremock/com/google/common/collect/ListMultimap

Without doing anything. Our project is a Spring Boot 2.2.1 with the latest Hoxton. Even using your version, or our version, or even importing 

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-wiremock</artifactId>
			<version>2.1.3.RELEASE</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-maven-plugin</artifactId>
			<version>2.1.3.RELEASE</version>
			<type>pom</type>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-contract-verifier</artifactId>
			<version>2.1.3.RELEASE</version>
			<scope>test</scope>
		</dependency>

Will not work.
Can you please help shed some light on this issue?
Thank you for your help.

**Comment by wkorando** [comment]
@patpatpat123 I'm glad you enjoyed my presentation and you using this code example to help solve a problem at your organization! 

Just checked on my local it works... because I had a change on my local that I for got to commit and push. 🤦‍♂️

Just pushed that change to the repo, so try another pull and that should resolve it. 

Be happy to hear any feedback, particularly how I could add to this project to make it more useful in real world scenarios. It can be hard to simulate the weirdness and complexity of the enterprise.
